### ISSUE TITLE
I am facing an error 

### ISSUE THREAD

**Issue by mariofaragalla** [ahasselbring/motorsoftware#1]
Hello !
I am working on the same project right now on Linux. I have updated the RTsync.c and Motor001.cpp files from your repository and now I am getting this error "Could not open tty". Do you know what could be the solution? Thank you. 

![Screenshot from 2020-07-17 14-10-16](https://user-images.githubusercontent.com/55330224/87785344-4df75500-c838-11ea-9f28-839f0569f77f.png)

**Comment by ahasselbring** [comment]
Hi,
most likely the reason is that your user does not have permissions to access `/dev/ttyACM0` (or whatever the device is called). If things on Ubuntu are still as they were three years ago, then adding yourself to the group `dialout`, e.g. by running `gpasswd -a <your username> dialout`, will solve the problem. Note that you have to log-out and re-log-in in order to let the group change take effect. If that doesn't help, check whether the file `/dev/ttyACM0` actually exists (it should exist as long as the board is plugged in) and what the permissions on it are (`ls -l /dev/ttyACM0`), or whether there are other devices called `/dev/ttyACM*`.

**Comment by mariofaragalla** [comment]
Hi ahasselbring,

Thank you very much for your help. After trying `sudo gpasswd -a <your username> dialout` the motor finally worked.
